# Generated by Django 5.1.7 on 2025-05-05 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='last_restocked',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
