# Generated by Django 5.1.7 on 2025-04-13 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='location',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='store',
            old_name='number',
            new_name='contact',
        ),
        migrations.RemoveField(
            model_name='store',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='store',
            name='lng',
        ),
        migrations.AddField(
            model_name='store',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20),
        ),
        migrations.AlterField(
            model_name='store',
            name='day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], default='Monday', max_length=20),
        ),
    ]
